name: namaz_kuran_app
description: Konuma göre namaz vakitleri ve Kuran-ı Kerim okuma uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_compass: ^0.8.1
  geocoding: ^3.0.0
  google_mobile_ads: ^7.0.0
  flutter_tts: ^4.0.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
